name:          BigWing Engineering Best Practices
title:         BigWing Engineering Best Practices
description:   Project engineering best practices used by BigWing.
url:           http://pages.bigwing.io/
baseurl:       /engineering-best-practices/public
author:
  name:    BigWing
  email:   wordpress@bigwing.com
  github:  BigWing
  twitter: BigWingAgency

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
